From node:14.17-alpine
MAINTAINER Vaibhav Bajpai

LABEL description = "Docker file for News App Assignment"

RUN mkdir -p /usr/src/logs
WORKDIR /usr/src
ADD . /usr/src

RUN mkdir -p /logs

RUN apk update && apk upgrade
RUN npm i

EXPOSE 3000

CMD ["npm","start"]